name: Build and deploy

on:
  push:
    branches:
      - masterXXX
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true

      - name: Build
        run: hugo --baseURL https://www.gentsebc.be/poc_gh_actions/ --minify

      - uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-file: './public/wp-config.php'
          _format-key: '%%key%%'
          dbname: ${{ secrets.REMOTE_DB_NAME }}
          dbuser: ${{ secrets.REMOTE_DB_USER }}
          dbpassword: ${{ secrets.REMOTE_DB_PASSWORD }}

      - name: SFTP mirror
        if: github.ref == 'refs/heads/master'
        uses: verbindingsfout/sftp-mirror@v1.6
        with:
          server: ${{ secrets.REMOTE_SFTP_HOST }}
          user: ${{ secrets.REMOTE_SFTP_USER }}
          password: ${{ secrets.REMOTE_SFTP_PWD }}
          port: 22
          local: ./public/
          remote: /customers/2/3/0/gentsebc.be/httpd.www/poc_gh_actions/