name: Build and deploy

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.9'
          extended: true

      - name: Cache hugo _gen directory
        uses: actions/cache@v3
        with:
          path: resources/_gen
          key: ${{ runner.os }}-hugogen-${{ hashFiles('resources/_gen/**') }}
          restore-keys: |
            ${{ runner.os }}-hugogen-

      - name: Build site with hugo
        run: hugo --baseURL https://www.gentsebc.be/ --minify

      - name: Setup SSH, install SSH Key
        if: github.ref == 'refs/heads/master'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Settup SSH, adding Known Hosts
        if: github.ref == 'refs/heads/master'
        run: ssh-keyscan -p ${{ secrets.REMOTE_SSH_PORT}} -H ${{ secrets.REMOTE_SSH_HOST }}  >> ~/.ssh/known_hosts

      - name: Build site with hugo
        run: hugo --baseURL https://www.gentsebc.be/ --minify

      - name: Set config values into template
        if: github.ref == 'refs/heads/master'
        uses: bluwy/substitute-string-action@v1
        id: sub
        with:
          _input-file: './public/wp-config-template.php'
          _format-key: '%%key%%'
          _output-file: './public/wp-config.php'
          dbname: ${{ secrets.REMOTE_DB_NAME }}
          dbuser: ${{ secrets.REMOTE_DB_USER }}
          dbpassword: ${{ secrets.REMOTE_DB_PASSWORD }}
          recaptchasitesecret: ${{ secrets.RECAPTCHA_SITE_SECRET }}

      - name: Deploy with rsync
        if: github.ref == 'refs/heads/master'
        run: rsync -avz --checksum --delete -e "ssh -p ${{ secrets.REMOTE_SSH_PORT }}" ./public/ ${{ secrets.REMOTE_SSH_USER }}@${{ secrets.REMOTE_SSH_HOST }}:/customers/2/3/0/gentsebc.be/httpd.www/
