name: Update calendars (WIP)
on: 
  workflow_dispatch:
  schedule:
    # 0 5 * * 1,3,5:  Every monday, wednesday, friday at 5AM"
    - cron: "0 3 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}    
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN_THOMAS }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install dayjs       
      - uses: actions/github-script@v6
        id: short-term-calendar
        with:
          script: |
            const script = require('./.github/scripts/download-agenda-data.js')
            const dayjs = require('dayjs')
            require('dayjs/locale/nl-be')
            await script({github, core, context, io, fetch, dayjs})
      - name: Get result
        run: |
          echo "${{steps.short-term-calendar.outputs.calendar-json}}" > static/shortTermCalendarV2.json

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add static/shortTermCalendarV2.json

          set +e  # Grep succeeds with nonzero exit codes to show results.
          git status | grep modified
          if [ $? -eq 0 ]
          then
              set -e
              git commit -am "shortTermCalendar update - $(date)"
              git push
          else
              set -e
              echo "No changes since last run"
          fi